import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { requireAuthenticatedUser } from "@/lib/auth/authorization";
import { INSTITUTION_MANAGEMENT_ROLES } from "@/lib/auth/institution-permissions";
import { listInstitutionRoadmaps } from "@/lib/institution/list-institution-roadmaps";

export const metadata: Metadata = {
  title: "Institution Roadmaps | CaseCompass AI",
};

/** Titles and ownership only — never step content or intake narrative, which stays private to the owning user. */
export default async function InstitutionRoadmapsPage() {
  const authResult = await requireAuthenticatedUser({ roles: INSTITUTION_MANAGEMENT_ROLES });
  if (!authResult.ok) {
    redirect(authResult.redirectTo);
  }
  if (!authResult.user.institutionId) {
    redirect("/institution/login");
  }

  const roadmaps = await listInstitutionRoadmaps(authResult.user.institutionId);

  return (
    <div className="mx-auto flex max-w-5xl flex-col gap-6">
      <div>
        <h1 className="text-2xl font-bold text-cc-text">Roadmaps</h1>
        <p className="mt-1 text-sm text-cc-muted">
          Research roadmaps generated by your institution&apos;s users. Titles and dates only — roadmap content stays
          private to each user.
        </p>
      </div>

      <div className="glass-card rounded-2xl p-6">
        {roadmaps.length === 0 ? (
          <p className="text-sm text-cc-muted">No roadmaps have been generated yet.</p>
        ) : (
          <ul className="flex flex-col divide-y divide-white/[0.06]">
            {roadmaps.map((roadmap) => (
              <li key={roadmap.id} className="flex items-center justify-between py-3">
                <div>
                  <p className="text-sm font-medium text-cc-text">{roadmap.title}</p>
                  <p className="text-xs text-cc-muted">{roadmap.ownerLabel}</p>
                </div>
                <span className="text-xs text-cc-muted">{new Date(roadmap.createdAt).toLocaleDateString()}</span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
